services: 
 app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-app
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: 'news-database'
      POSTGRES_PORT: '5432'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'news_development'

networks:
  default:
    external:
      name: appserver_default